### ISSUE TITLE
抢购时返回登录界面

### ISSUE THREAD

**Issue by xuexin** [ghwswywps/jd_seckill#12]
我打印了response，结果是一个登录页面？
见附件
[response.txt](https://github.com/ghwswywps/jd_seckill/files/5713211/response.txt)

**Comment by Jerrypoi** [comment]
是不是没带 thor 这个 cookie？

**Comment by xuexin** [comment]
带了，监控那边都可以拿到我的账号名

**Comment by ghwswywps** [comment]
> response.txt

line多少的response？

**Comment by xuexin** [comment]
> > response.txt
> 
> line多少的response？


#post请求，提交订单
response = item.session.post(url=item.pay_success, headers=JD.headers)
print(response.text)

**Comment by jsxzBillLee** [comment]
建议你在需要跑脚本的机器上，或者同一个网络内的其他机器上，用网页多登录几次。

**Comment by jsxzBillLee** [comment]
> 我打印了response，结果是一个登录页面？
> 见附件
> [response.txt](https://github.com/ghwswywps/jd_seckill/files/5713211/response.txt)

建议你在需要跑脚本的机器上，或者同一个网络内的其他机器上，用网页多登录几次。然后再获取cookie。我之前好像遇到过，应该是京东那边认为你的请求不是来自常用ip导致的。

**Comment by jsxzBillLee** [comment]
另外如果cookie失效了，还是能拿到昵称的，但是下单等请求会提示要求登录。

**Comment by xuexin** [comment]
> 另外如果cookie失效了，还是能拿到昵称的，但是下单等请求会提示要求登录。

好，我试试

**Comment by xuexin** [comment]
没有比较方便的方法判断cookie是否有效吗？

**Comment by xuexin** [comment]
重新拿cookie正常了
