### ISSUE TITLE
win下面的time_sync似乎没有用？

### ISSUE THREAD

**Issue by zherlock030** [ghwswywps/jd_seckill#14]
linux下有一个system cmd执行，而win下面好像只看到了时间输出没有时间的校准。
另外想问，如果做不到精准的时间校准，是不是只要把time_diff设置的大一点，在抢购之前，触发shopping的循环就可以？

**Comment by jsxzBillLee** [comment]
win32api.SetSystemTime(tm_year, tm_mon, tm_wday, tm_mday, tm_hour, tm_min, tm_sec, int(msec))

**Comment by jsxzBillLee** [comment]
> linux下有一个system cmd执行，而win下面好像只看到了时间输出没有时间的校准。

win32api.SetSystemTime(tm_year, tm_mon, tm_wday, tm_mday, tm_hour, tm_min, tm_sec, int(msec))

**Comment by jsxzBillLee** [comment]
> 另外想问，如果做不到精准的时间校准，是不是只要把time_diff设置的大一点，在抢购之前，触发shopping的循环就可以？
A：建议随便找几个个需要抢购的商品，调教一下time_diff，保证下单提交不会被京东拒绝的前提下，尽量提前抢购。
具体的提前量，还是需要自己多试几次的。因为每个人的物理距离导致的延迟是不一样的，还要考虑中间加购车等一系列操作的延时。
发K老黄和奸商。

**Comment by zherlock030** [comment]
@jsxzBillLee 谢谢老哥，再去试试，不过现在是没有3060ti让我抢了，真的离谱。
