### ISSUE TITLE
如何配置 thor

### ISSUE THREAD

**Issue by 97wow** [ghwswywps/jd_seckill#5]
作者好，同3080抢购需求，请问 如何配置 thor

配置好python后运行是这样，卡在倒计时。
感谢解答。
![image](https://user-images.githubusercontent.com/11026453/96375758-7a12d100-11ad-11eb-8a02-065a6e70bbe6.png)

**Comment by ZRory** [comment]
抢不到...烦

**Comment by ghwswywps** [comment]
每次放货10张抢个鸡毛 我已经上3090了

**Comment by ZRory** [comment]
...我准备49年入国军了

**Comment by 97wow** [comment]
一咬牙一跺脚 上了3090~。~
问题是3090也抢不到啊

**Comment by ghwswywps** [comment]
京东自营丐 微信 12999原价现货 12期免息 等于白送 哈哈哈

**Comment by ghwswywps** [comment]
> thor

脚本里有thor = '' 从你登陆京东页面里的cookie里拿到thor 粘贴进去就行

**Comment by 97wow** [comment]
> 京东自营丐微信12999原价现货12期免息等于白送哈哈哈

可否加告诉我微信多少 我也直接3090算了
我微信 huyazhou
直接搜索这个就能找到我。

**Comment by ghwswywps** [comment]
> > 京东自营丐微信12999原价现货12期免息等于白送哈哈哈
> 
> 可否加告诉我微信多少 我也直接3090算了
> 我微信 huyazhou
> 直接搜索这个就能找到我。

OK
