### ISSUE TITLE
thor可以有效多长时间？

### ISSUE THREAD

**Issue by EndyZhou** [ghwswywps/jd_seckill#7]
当我获取ck之后似乎thor一天就过期了

**Comment by ghwswywps** [comment]
测试的时候试过2天没过期，再长没有试过了。不打算研究了，现在这个脚本容易抢到官方加价版本，感觉没之前实用了，推荐需要抢的时候再开 然后链接换成想要显卡的指定页面，不用去考虑过期问题。

**Comment by reddloob** [comment]
> 测试的时候试过2天没过期，再长没有试过了。不打算研究了，现在这个脚本容易抢到官方加价版本，感觉没之前实用了，推荐需要抢的时候再开 然后链接换成想要显卡的指定页面，不用去考虑过期问题。

请问如何同步京东服务器的时间？

**Comment by dos2002** [comment]
> > 测试的时候试过2天没过期，再长没有试过了。不打算研究了，现在这个脚本容易抢到官方加价版本，感觉没之前实用了，推荐需要抢的时候再开 然后链接换成想要显卡的指定页面，不用去考虑过期问题。
> 
> 请问如何同步京东服务器的时间？

运行：jd_time_sync_win.py  依赖：   
     pip install pypiwin32
    pip install requests

**Comment by reddloob** [comment]
> > > 测试的时候试过2天没过期，再长没有试过了。不打算研究了，现在这个脚本容易抢到官方加价版本，感觉没之前实用了，推荐需要抢的时候再开 然后链接换成想要显卡的指定页面，不用去考虑过期问题。
> > 
> > 
> > 请问如何同步京东服务器的时间？
> 
> 运行：jd_time_sync_win.py 依赖：
> pip install pypiwin32
> pip install requests

谢谢。请问linux怎么同步京东时间？

**Comment by ghwswywps** [comment]
之前已经将京东服务时间修正加入脚本，不需要额外同步，具体参考line 68
