### ISSUE TITLE
访问时 https://passport.jd.com  返回302.

### ISSUE THREAD

**Issue by danwey** [ghwswywps/jd_seckill#8]
在 def login(self):  方法里面的。

**Comment by ghwswywps** [comment]
本地没有复现，需要提供下具体返回信息

**Comment by danwey** [comment]
curl https://passport.jd.com/user/petName/getUserInfoForMiniJd.action\?\&callback\=jsonpUserinfo\&_\=1606984707481
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by danwey** [comment]
主要问题是：
        #1通过session获取用户信息
        user_url = self.user_url
        print(user_url)
打印出来的内容：
{'imgUrl': '//passport.jd.com/new/misc/skin/df/i/no-img_mid_.jpg', 'userLevel': 1, 'plusStatus': '0', 'realName': '', 'nickName': '', 'lastLoginTime': ''}

if self.user_info.get('nickName'):
拿不到nickName。跑不进：_thread.start_new_thread
所以我找了一下self.user_info的定义。找到了 https://passport.jd.com/user/petName/getUserInfoForMiniJd.action\?\&callback\=jsonpUserinfo\&_\=1606984707481。然后curl了一下。返回302。所以来求助。

**Comment by ghwswywps** [comment]
我使用无效的thor发现必现此问题，已经加入异常提醒，可以检查下thor是否还可用

**Comment by ghwswywps** [comment]
推荐http://www.editthiscookie.com/插件 检测cookie生效状态 close
