### ISSUE TITLE
tuf plus限定的能用吗

### ISSUE THREAD

**Issue by 120216220** [ghwswywps/jd_seckill#9]

**Comment by Icarusradio** [comment]
手动添加 `self.config`，不过没啥用，还是抢不到

**Comment by 120216220** [comment]
你还没抢到吗？本来打算今年组电脑的~才发现啥都买不到，一直耍猴，昨天没抢到就打算自己写个脚本试试了~emmmm~聊胜于无吧，不知道jd是不是按token已经随机过滤掉一波人了

**Comment by Icarusradio** [comment]
手动加了好几个卡（各种丐版 3060Ti 3070 3080）反正没抢到。
不过很奇怪的是看运行打的 log 一直显示“第 4 次尝试”。按照代码逻辑不应该尝试次数不停增加，到 100 次停下来么。

**Comment by ghwswywps** [comment]
> 手动加了好几个卡（各种丐版 3060Ti 3070 3080）反正没抢到。
> 不过很奇怪的是看运行打的 log 一直显示“第 4 次尝试”。按照代码逻辑不应该尝试次数不停增加，到 100 次停下来么。

实测日志显示的有问题但不影响抢购，前面的老哥修复购物车bug的时候出现了这个问题，一直没时间去看为什么日志会卡住，如果要确定是否被风控可以把抢购的rep打印出来，如果抢到卡被风控会直接显示你被风控了，已经损失3个号

**Comment by ghwswywps** [comment]
> 手动加了好几个卡（各种丐版 3060Ti 3070 3080）反正没抢到。
> 不过很奇怪的是看运行打的 log 一直显示“第 4 次尝试”。按照代码逻辑不应该尝试次数不停增加，到 100 次停下来么。

这个重复问题找到了，等下次验证完push

**Comment by 120216220** [comment]
> > 手动加了好几个卡（各种丐版 3060Ti 3070 3080）反正没抢到。
> > 不过很奇怪的是看运行打的 log 一直显示“第 4 次尝试”。按照代码逻辑不应该尝试次数不停增加，到 100 次停下来么。
> 
> 实测日志显示的有问题但不影响抢购，前面的老哥修复购物车bug的时候出现了这个问题，一直没时间去看为什么日志会卡住，如果要确定是否被风控可以把抢购的rep打印出来，如果抢到卡被风控会直接显示你被风控了，已经损失3个号

噗，是黑号了？申请客服解封去？

**Comment by Icarusradio** [comment]
> > 手动加了好几个卡（各种丐版 3060Ti 3070 3080）反正没抢到。
> > 不过很奇怪的是看运行打的 log 一直显示“第 4 次尝试”。按照代码逻辑不应该尝试次数不停增加，到 100 次停下来么。
> 
> 实测日志显示的有问题但不影响抢购，前面的老哥修复购物车bug的时候出现了这个问题，一直没时间去看为什么日志会卡住，如果要确定是否被风控可以把抢购的rep打印出来，如果抢到卡被风控会直接显示你被风控了，已经损失3个号

哈哈，默哀。
反正也没包太大希望，毕竟黄牛有更猛的软件，试试玩玩。新卡是不可能买的了，这辈子都不可能的（x

**Comment by ghwswywps** [comment]
> > > 手动加了好几个卡（各种丐版 3060Ti 3070 3080）反正没抢到。
> > > 不过很奇怪的是看运行打的 log 一直显示“第 4 次尝试”。按照代码逻辑不应该尝试次数不停增加，到 100 次停下来么。
> > 
> > 
> > 实测日志显示的有问题但不影响抢购，前面的老哥修复购物车bug的时候出现了这个问题，一直没时间去看为什么日志会卡住，如果要确定是否被风控可以把抢购的rep打印出来，如果抢到卡被风控会直接显示你被风控了，已经损失3个号
> 
> 噗，是黑号了？申请客服解封去？

没用的，反正紧俏商品抢到就风控，也不知道什么时候出黑名单。。

**Comment by ghwswywps** [comment]
对了 关于plus限定是否能用这个问题没有验证，我抢到的时候还没有plus限定，不过开启plus限定后确实再也没抢到过，我估计是被限制住了，有兴趣可以研究下。
